services:
  db:
    image: mysql:8
    container_name: gamchi-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gamchi
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - gamchi-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: ${IMAGE_TAG}
    container_name: gamchi-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - gamchi-network
    restart: always
    env_file:
      - .env

volumes:
  mysql_data:
    external: true

networks:
  gamchi-network:
    driver: bridge
