spring:
  application:
    name: team-ace-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/gamchi
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true
  ai:
    model:
      chat: none # 기본 모델 설정 비활성화
    openai:
      api-key: ${OPENAI_API_KEY:fake-key} # 기본 모델을 비활성화해도 필수값으로 받음.

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      log-format: "%(executionTime)ms | %(category) | %(sql)"


jwt:
  secret: ${JWT_SECRET:dGVhbS1hY2UtYmFja2VuZC1kZWZhdWx0LXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50LW9ubHk=}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:3600000}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:604800000}

gemini:
  api-key: ${GEMINI_API_KEY:test-api-key}
  model: gemini-2.0-flash-exp
