name: Continuous Integration

on:
  pull_request: # PR 단계에서 해당 브랜치의 소스가 문제 없음을 보장하기 위함
    branches:
      - main
  push: # Merge 후 main 브랜치의 소스가 문제 없음을 보장하기 위함
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'oracle'

      - name: Setup Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew test

      - name: Publish Test Results When Test Fails
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ failure() }}
        with:
          files: build/test-results/**/*.xml
